name: Build and Release

on:
  push:
    branches:
      - main
    paths:
      - 'jiaz/**'
      - 'requirements.txt'

jobs:
  build:
    needs: [lint, code-quality, test]
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build binary with PyInstaller
        run: |
          pyinstaller --clean --onefile jiaz/__main__.py --name jiaz

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: jiaz-${{ matrix.os }}
          path: dist/jiaz*
