name: Cleanup Artifacts (Master Only)

on:
  schedule:
    - cron: '59 23 * * *'  # Every day at 11:59 PM UTC
  push:
    paths:
      - '.github/workflows/cleanup.yaml'

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Find latest successful run for master
        id: latest_run
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const runs = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: "master",
              status: "success",
              per_page: 1
            });
            if (runs.data.workflow_runs.length > 0) {
              core.setOutput("run_id", runs.data.workflow_runs[0].id);
            } else {
              core.setOutput("run_id", "");
            }

      - name: Delete artifacts except for latest successful master run and log details
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const formatBytes = require('./.github/workflows/formatBytes.js');
            const runId = process.env.RUN_ID;
            const artifactsResponse = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const artifacts = artifactsResponse.data.artifacts;

            if (!artifacts.length) {
              console.log('[CLEANUP] No artifacts found in the repository.');
              return;
            }

            let totalCleaned = 0;
            let deletedCount = 0;
            for (const artifact of artifacts) {
              if (runId && String(artifact.workflow_run.id) !== String(runId)) {
                await github.rest.actions.deleteArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: artifact.id
                });
                totalCleaned += artifact.size_in_bytes;
                deletedCount += 1;
                console.log(`[CLEANUP] Deleted artifact: ${artifact.name} (${formatBytes(artifact.size_in_bytes)})`);
              }
            }

            if (deletedCount === 0) {
              console.log('[CLEANUP] No artifacts were deleted (all retained or none matched criteria).');
            } else {
              console.log(`[CLEANUP] Total space cleaned: ${formatBytes(totalCleaned)}`);
            }

            // Get remaining artifacts for space left
            const remainingArtifacts = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            let totalLeft = 0;
            for (const artifact of remainingArtifacts.data.artifacts) {
              totalLeft += artifact.size_in_bytes;
            }
            console.log(`[CLEANUP] Total space used by remaining artifacts: ${formatBytes(totalLeft)}`);
        env:
          RUN_ID: ${{ steps.latest_run.outputs.run_id }}
